image: docker:latest

variables:
  DOCKER_DRIVER: overlay
  VERSION: 3.5.2
  TAG: ${VERSION}-alpine
  TAG_MINOR: 3.5-alpine
  TAG_MAJOR: 3-alpine
  VCS_REF: ${CI_BUILD_REF}

services:
  - docker:dind

before_script:
  - docker info
  - docker login ${CI_REGISTRY} -u gitlab-ci-token -p ${CI_BUILD_TOKEN}


stages:
  - build
  - test
  - deploy

image-build:
  stage: build
  script:
    - docker build 
      --build-arg BUILD_DATE=${BUILD_DATE} 
      --build-arg VCS_REF=${VCS_REF} 
      --build-arg VERSION=${VERSION} 
      --rm -t ${CI_REGISTRY}/smizy/python:${TAG} .
    - docker images | grep python
    - docker push ${CI_REGISTRY}/smizy/python:${TAG}

image-test:
  stage: test
  script:
    - docker inspect ${CI_REGISTRY}/smizy/python:${TAG}
    - docker run ${CI_REGISTRY}/smizy/python:${TAG} python --version

image-deploy:
  stage: deploy
  script:
    - docker pull ${CI_REGISTRY}/smizy/python:${TAG}
    - docker logout
    - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
    - docker tag smizy/python:${TAG} smizy/python
    - docker tag smizy/python:${TAG} smizy/python:${TAG_MINOR}
    - docker tag smizy/python:${TAG} smizy/python:${TAG_MAJOR}
    - docker push smizy/python:${TAG}
    - docker push smizy/python:${TAG_MINOR}
    - docker push smizy/python:${TAG_MAJOR}
    - docker push smizy/python:latest
    - docker logout
    - curl -X POST 'https://hooks.microbadger.com/images/smizy/python/B67xdho_HXXeXxVkUjT0TlgEmjk='