image: docker:latest

variables:
  DOCKER_DRIVER: overlay
  VERSION: 3.6.1
  TAG: ${VERSION}-alpine
  TAG_MINOR: 3.6-alpine
  TAG_MAJOR: 3-alpine
  VCS_REF: ${CI_BUILD_REF}
  CONTAINER_IMAGE: ${CI_REGISTRY}/smizy/python

services:
  - docker:dind

before_script:
  - docker info
  - docker login -u gitlab-ci-token -p ${CI_BUILD_TOKEN} $CI_REGISTRY


stages:
  - build
  - test
  - deploy

image-build:
  stage: build
  script:
    - docker build 
      --build-arg BUILD_DATE=${BUILD_DATE} 
      --build-arg VCS_REF=${VCS_REF} 
      --build-arg VERSION=${VERSION} 
      --rm -t ${CONTAINER_IMAGE} .
    - docker images | grep python
    - docker push ${CONTAINER_IMAGE} # fail

image-test:
  stage: test
  script:
    - docker pull ${CONTAINER_IMAGE}
    - docker inspect ${CONTAINER_IMAGE}
    - docker run ${CONTAINER_IMAGE} python --version

image-deploy:
  stage: deploy
  script:
    - docker pull ${CONTAINER_IMAGE}
    - docker tag ${CONTAINER_IMAGE} ${CONTAINER_IMAGE}:${TAG}
    - docker tag ${CONTAINER_IMAGE} ${CONTAINER_IMAGE}:${TAG_MINOR}
    - docker tag ${CONTAINER_IMAGE} ${CONTAINER_IMAGE}:${TAG_MAJOR}
    - docker push ${CONTAINER_IMAGE}:${TAG}
    - docker push ${CONTAINER_IMAGE}:${TAG_MINOR}
#    - docker push ${CONTAINER_IMAGE}:${TAG_MAJOR}
    - docker logout
    - docker login -e ${DOCKER_EMAIL} -u ${DOCKER_USER} -p ${DOCKER_PASS}
    - docker push ${CONTAINER_IMAGE}:${TAG}
    - docker push ${CONTAINER_IMAGE}:${TAG_MINOR}
 #   - docker push ${CONTAINER_IMAGE}:${TAG_MAJOR}
 #   - docker push ${CONTAINER_IMAGE}
    - docker logout
    - curl -X POST 'https://hooks.microbadger.com/images/smizy/python/B67xdho_HXXeXxVkUjT0TlgEmjk='