version: 2
jobs:
  build:
    working_directory: ~/deps

    docker:
      - image: docker:20.10.14-git

    environment:
      VERSION: "3.10.5"
      TAG: "3.10.5-alpine"
      # TAG: ${VERSION}-alpine
      # TAG_MINOR: ${VERSION%.*}-alpine
      # TAG_MAJOR: ${VERSION%%.*}-alpine 
      # BUILD_DATE: $(date -u +"%Y-%m-%dT%H:%M:%SZ")
      VCS_REF: ${CIRCLE_SHA1}
      BATS_VER: "0.4.0"  

    steps:
      - checkout

      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true         

      - run:
          name: install dependencies - lib
          command: |
            apk --no-cache add \
              bash \
              curl \
              curl-dev \
              make

      - run:
          name: install dependencies - bats
          command: |
            dir=${CIRCLE_WORKING_DIRECTORY}
            mkdir -p ${dir}

            if [[ ! -e ${dir}/bats_v${BATS_VER}.tar.gz ]]; then 
              curl -sSL -o ${dir}/bats_v${BATS_VER}.tar.gz https://github.com/sstephenson/bats/archive/v${BATS_VER}.tar.gz
            fi
            
            tar -xf ${dir}/bats_v${BATS_VER}.tar.gz
            bats-${BATS_VER}/install.sh /usr/local

      - run:
          name: docker client and remote info
          command: |
            docker version
            docker info

      - run:
          name: docker image build
          command: make all

      - run:
          name: test
          command: |
            docker inspect smizy/python:${TAG}
            make test

      - run:
          name: docker image push
          command: |
            TAG_MINOR=${VERSION%.*}-alpine
            TAG_MAJOR=${VERSION%%.*}-alpine

            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker image tag smizy/python:${TAG} smizy/python
            docker image push smizy/python:${TAG}

            docker image tag smizy/python:${TAG} smizy/python:${TAG_MINOR}
            docker image push smizy/python:${TAG_MINOR}

            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker image push smizy/python:latest 
            fi
                     
            docker logout
